### ISSUE TITLE
extractCleanGridSpyCircuit 

### ISSUE THREAD

**Issue by raffertyparker** [CfSOtago/GREENGridData#22]
extractCleanGridSpyCircuit is having problems with rf_15
>Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 4 columns, inconsistent with item 1 which has 5 columns. To fill missing columns use fill=TRUE.
>In addition: Warning message:
The following named parsers don't match the column names: linkID 

When I delete rf_15 as per instructions here https://github.com/CfSOtago/GREENGridData/issues/19 it also fails with error message:

>Error: '~/HWC-bookdown/Masters/powerData/rf_15_all_1min_data.csv.gz' does not exist.

**Comment by dataknut** [comment]
the first error is probably caused by rf_15 being malformed data (it should have been split before release). The second should not occur if you delete the rf_15 file because the extractCleanGridSpyCircuit() function should get the file list fresh each time since you pass it the path to check.

**Comment by raffertyparker** [comment]
Tried it again using the extractCircuitFromCleanGridSpy1min.R script and it is working fine. Yesterday I was calling from the command line, perhaps that was the problem.
