### ISSUE TITLE
Answers to questions not 'making sense'

### ISSUE THREAD

**Issue by RaffertyP** [CfSOtago/GREENGridData#46]
![image](https://user-images.githubusercontent.com/66574415/97663641-fcb95b80-1ade-11eb-9f65-6397ed24a175.png)
![image](https://user-images.githubusercontent.com/66574415/97663666-0e9afe80-1adf-11eb-84cd-2ce0383d3e35.png)
The answers provided in ggHouseholdAttributesSafe.csv don't always make sense in the context of the questions given in Table 9.1 of NZ_GREEN_GridHouseholdElectricityDemandStudy_HouseholdAttributeData_v1.0.pdf. An example is provided in the images that seems to imply everyone has a heated swimming pool, 3 toasters, either 1 or three top-loader washing machines AND either 1 or 3 front-loaders, etc. Am I interpreting something wrong?

**Comment by RaffertyP** [comment]
Also, Q7 "When was your house built?" has answers ranging 1 through 4.

**Comment by dataknut** [comment]
Q7 is a banded scale - see https://cfsotago.github.io/GREENGridData/EC2HouseholdSurveyAsUsedInGG.pdf

**Comment by dataknut** [comment]
LOL. Q40 is a 3 item response: 

  | Do not own (1) | Own and never use (2) | Own and use (3)

again, see that pdf.

**Comment by dataknut** [comment]
Sorry, I only managed to get that EC2 survey pdf on to github last week. It's now linked on https://cfsotago.github.io/GREENGridData/ <- second bullet down

**Comment by RaffertyP** [comment]
I figured it would be something like that. Thanks Ben!
